default_profile = "chronos"

[profiles]
[profiles.chronos]
cfg_dir = "/home/mepholic/.config/awesome/"
theme_dir = "powerarrowf/"
theme_script = "theme.lua"
browser = "google-chrome"
editor = "emacs"
terminal = "urxvt256c"
font = "Inconsolata 11"
battery = false
fs_mon = "/home"
if_wired = "em1"
if_wlan = ""
alsa_name = "Master"
[profiles.work]
cfg_dir = "/home/meph/.config/awesome/"
theme_dir = "powerarrowf/"
theme_script = "theme.lua"
browser = "google-chrome"
editor = "emacs"
terminal = "urxvt256c"
font = "Incognito 11"
battery = false
fs_mon = "/"
if_wired = "eth0"
if_wlan = ""
alsa_name = "Master"
tags = [ ["term", "term", "voip", "remote", "misc", "misc"], ["web", "mail", "bim", "slack", "misc", "misc"] ]
