
[default_profile]
cfg_dir = "/home/mepholic/.config/awesome/"
theme_dir = "powerarrowf/"
theme_script = "theme.lua"
panel_size = "16"
panel_pos = "top"
browser = "google-chrome"
editor = "emacs"
terminal = "urxvt256c"
font = "Inconsolata 11"
batt_name = ""
fs_mon = "/home"
if_wired = "eth0"
if_wlan = ""
alsa_name = "Master"
tags = [ [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ] ]
wallpaper = [ "/home/mepholic/.config/awesome/res/candy_bean_wallpaper.jpg" ]
xrandr_cfg = ""
xrandr_pri = ""


[profiles]

[profiles.chronos]
terminal = "urxvt"
if_wired = "enp2s0"
browser = "google-chrome-unstable"
tags = [ [ "term", "web", "mail", "chat", "bim", "misc", "misc", "music" ] ]
wallpaper = [ "/home/mepholic/.config/awesome/res/club_aurigia.jpg" ]
xrandr_pri = "DVI-I-2"

[profiles.darklord]
terminal = "urxvt"
fs_mon = "/"
if_wlan = "wlan0"
batt_name = "BAT1"
tags = [ [ "term", "web", "chat", "mail", "misc", "misc", "music" ] ]
wallpaper = [ "/home/mepholic/.config/awesome/res/club_aurigia.jpg" ]

[profiles.work]
cfg_dir = "/home/dtheisen/.config/awesome/"
terminal = "urxvt"
fs_mon = "/"
tags = [ [ "web", "mail", "bim", "slack", "misc", "misc" ], [ "term", "term", "voip", "remote", "misc", "misc" ] ]
wallpaper = [ "/home/dtheisen/.config/awesome/res/SpaceStationPanelsEVAEarth.jpg", "/home/dtheisen/.config/awesome/res/SpaceSlothSunglasses.jpg" ]
xrandr_cfg = [ [ "HDMI-1", "DVI-I-1", "--right-of", "HDMI-1" ] ]
xrandr_pri = "HDMI-1"
awful_rules = false
