default_profile = "chronos"

[profiles]
[profiles.chronos]
cfg_dir = "/home/mepholic/.config/awesome/"
theme_dir = "powerarrowf/"
theme_script = "theme.lua"
font = "Inconsolata 11"
battery = false
fs_mon = "/home"
if_wired = "em1"
if_wlan = ""
alsa_name = "Master"
[profiles.work]
cfg_dir = "/home/meph/.config/awesome/"
theme_dir = "powerarrowf/"
theme_script = "theme.lua"
font = "Incognito 11"
battery = false
fs_mon = "/"
if_wired = "eth0"
if_wlan = ""
alsa_name = "Master"
